development:
  adapter: sqlite3
  database: db/postie_development.sqlite3

test:
  adapter: sqlite3
  database: db/postie_test.sqlite3

production:
  adapter: sqlite3
  database: db/postie_production.sqlite3
